steps:
  - id: "Rodando o docker compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

  - id: "Chown na diretorio /var/www"
    name: "gcr.io/cloud-builders/docker"
    args: ['exec', '-u', 'root', '-t', 'app', 'chown', '-R', 'www-data:www-data', '/var/www']

  - id: 'Rodando o composer install'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'app', 'composer', 'install' ]

  - id: 'Fazendo a copia do .env'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

  - id: 'Gerando a key'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'app', 'php', 'artisan', 'key:generate' ]

  - id: 'Rodando as migrations'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'app', 'php', 'artisan', 'migrate' ]

  - id: 'Rodando os testes'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
